typedef struct dspobj DSPOBJ;
typedef struct msg MSG;
typedef struct button BUTTON;
typedef struct prompt PROMPT;
typedef struct pulldown PULLDOWN;
typedef struct pulitm PULITM;
typedef struct graph GRAPH;
typedef struct work WORK;
typedef struct help HELP;
typedef struct link LINK;
typedef size_t U;
typedef size_t SZ;
typedef ptrdiff_t I;
typedef char C;
typedef struct lst LST;
typedef struct num NUM;
typedef struct sym SYM;
typedef struct token TOKEN;
