/* This file utomatically generated by vcsr */
/* Do not edit: instead modify Verilog RTL */

#include "csrdef.h"

struct ctrl_t {
  _RdWr(i_l, 1, 2);
  _RdWr(j, 1, 1);
  _RdWr(k_l, 1, 0);
};

struct stat_t {
  _RdOnly(x, 12, 2);
  _RdOnly(y, 1, 1);
  _RdOnly(z_l, 1, 0);
};

struct status_t {
  _RdOnly(a, 2, 2);
  _RdOnly(b, 1, 1);
  _RdOnly(c, 1, 0);
};

struct example_t CHIP_COLLECTION {
  REGISTER(ctrl, ctrl_t, 0x55aa);
  REGISTER(stat, stat_t, 0x101);
  REGISTER(status, status_t, 0x12345);
} example;
